# datasource
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moving_pack
    username: devuser
    password: devpass

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

# external api
external:
  api:
    base-url: http://localhost:8081
